version: '3.4'

services:
  rabbitmq:
     image: rabbitmq:3-management-alpine
  gisa.ocelotapigateway:
    image: ${DOCKER_REGISTRY-}gisaocelotapigateway
    build:
      context: .
      dockerfile: src/ApiGateway/GISA.OcelotApiGateway/Dockerfile

  gisa.associado:
    image: ${DOCKER_REGISTRY-}gisaassociado
    build:
      context: .
      dockerfile: src/ModuloInformacaoCadastral/GISA.Associado/Dockerfile

  gisa.comunicacaolegado:
    image: ${DOCKER_REGISTRY-}gisacomunicacaolegado
    build:
      context: .
      dockerfile: src/ComunicacaoLegado/GISA.ComunicacaoLegado/Dockerfile


  gisa.prestador:
    image: ${DOCKER_REGISTRY-}gisaprestador
    build:
      context: .
      dockerfile: src/ModuloInformacaoCadastral/GISA.Prestador/Dockerfile